### ISSUE TITLE
Immediately closes in windows

### ISSUE THREAD

**Issue by Durvin** [OpenChartProject/OpenChart#100]
# 📖 Overview

from OpenChart.log:
[2020-12-23 12:38:30.756] INFO    ------------------------
[2020-12-23 12:38:30.774] INFO    Initializing...
[2020-12-23 12:38:30.774] DEBUG   Set current directory to E:\Openchart
[2020-12-23 12:38:30.775] DEBUG   Setting up file formats.
[2020-12-23 12:38:30.775] INFO    Finding noteskins...
[2020-12-23 12:38:30.869] ERROR   Exception while trying to load noteskin 'default_arrow'.
System.DllNotFoundException: Unable to load DLL 'SDL2_image' or one of its dependencies: Den angitte modulen ble ikke funnet. (0x8007007E)
   at SDL2.SDL_image.INTERNAL_IMG_Load(Byte* file)
   at SDL2.SDL_image.IMG_Load(String file)
   at OpenChart.UI.Surface.LoadFromFile(String path)
   at OpenChart.NoteSkins.NoteSkinManager.loadKeyModeSkin(NoteSkin noteSkin, Int32 keyCount, String path)
   at OpenChart.NoteSkins.NoteSkinManager.loadNoteSkin(String path, String skinName)
   at OpenChart.NoteSkins.NoteSkinManager.LoadAll(String path)
[2020-12-23 12:38:30.886] INFO    Ready.
[2020-12-23 12:38:30.886] INFO    Displaying main window.
[2020-12-23 12:38:30.941] FATAL   Uncaught exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at OpenChart.Application.Run()
   at OpenChart.Program.Main()

[2020-12-23 12:38:35.413] INFO    ------------------------
[2020-12-23 12:38:35.429] INFO    Initializing...
[2020-12-23 12:38:35.429] DEBUG   Set current directory to E:\Openchart
[2020-12-23 12:38:35.430] DEBUG   Setting up file formats.
[2020-12-23 12:38:35.430] INFO    Finding noteskins...
[2020-12-23 12:38:35.515] ERROR   Exception while trying to load noteskin 'default_arrow'.
System.DllNotFoundException: Unable to load DLL 'SDL2_image' or one of its dependencies: Den angitte modulen ble ikke funnet. (0x8007007E)
   at SDL2.SDL_image.INTERNAL_IMG_Load(Byte* file)
   at SDL2.SDL_image.IMG_Load(String file)
   at OpenChart.UI.Surface.LoadFromFile(String path)
   at OpenChart.NoteSkins.NoteSkinManager.loadKeyModeSkin(NoteSkin noteSkin, Int32 keyCount, String path)
   at OpenChart.NoteSkins.NoteSkinManager.loadNoteSkin(String path, String skinName)
   at OpenChart.NoteSkins.NoteSkinManager.LoadAll(String path)
[2020-12-23 12:38:35.523] INFO    Ready.
[2020-12-23 12:38:35.524] INFO    Displaying main window.
[2020-12-23 12:38:35.568] FATAL   Uncaught exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at OpenChart.Application.Run()
   at OpenChart.Program.Main()

Den angitte modulen ble ikke funnet --> The specified module was not found
I should also note that i tried to install this on my E:/ drive, and not on C:/

**Comment by Durvin** [comment]
Launching in admin makes no difference. Installing and launching in C:/ also makes no difference

**Comment by Kangaroux** [comment]
@Durvin Can you download the [SDL_Image DLLs](https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.5-win32-x64.zip), extract it next to openchart.exe, and try that?

**Comment by Durvin** [comment]
[2020-12-23 20:24:34.352] INFO    ------------------------
[2020-12-23 20:24:34.378] INFO    Initializing...
[2020-12-23 20:24:34.378] DEBUG   Set current directory to E:\Openchart
[2020-12-23 20:24:34.379] DEBUG   Setting up file formats.
[2020-12-23 20:24:34.379] INFO    Finding noteskins...
[2020-12-23 20:24:34.535] ERROR   Exception while trying to load noteskin 'default_arrow'.
System.TypeInitializationException: The type initializer for 'Cairo.NativeMethods' threw an exception.
 ---> System.DllNotFoundException: Cairo: libcairo-2.dll, libcairo.so.2, libcairo.2.dylib, cairo.dll
   at GLibrary.Load(Library library)
   at Cairo.NativeMethods..cctor()
   --- End of inner exception stack trace ---
   at Cairo.ImageSurface..ctor(IntPtr data, Format format, Int32 width, Int32 height, Int32 stride)
   at OpenChart.UI.Surface.createCairoSurface()
   at OpenChart.UI.Surface..ctor(IntPtr data, Boolean freeOnDispose)
   at OpenChart.UI.Surface.LoadFromFile(String path)
   at OpenChart.NoteSkins.NoteSkinManager.loadKeyModeSkin(NoteSkin noteSkin, Int32 keyCount, String path)
   at OpenChart.NoteSkins.NoteSkinManager.loadNoteSkin(String path, String skinName)
   at OpenChart.NoteSkins.NoteSkinManager.LoadAll(String path)
[2020-12-23 20:24:34.574] INFO    Ready.
[2020-12-23 20:24:34.574] INFO    Displaying main window.
[2020-12-23 20:24:34.622] FATAL   Uncaught exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at OpenChart.Application.Run()
   at OpenChart.Program.Main()

SDL2_image is now being found, but it is now complaining about some missing cairo DLLs
